steps:

- name: 'gcr.io/cloud-builders/npm:node-8.11.0'
  args: ['install']
  id: 'npm-install'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm:node-8.11.0'
  args: ['run', 'build-docs']
  id: 'ng-build-docs'
  waitFor: ['npm-install']

artifacts:
  objects:
    location: 'gs://vendasta-material-docs'
    paths: ['tmp/material-docs-*.tar.gz']

timeout: 1200s
options:
  machineType: N1_HIGHCPU_8
